name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "516f699a5c79f20acbbe47ae23010000005ef2adfa76952831e1f20d7a0e1b25"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
