name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3e5a23f2950dd100187a5d140fd0f031b5f448d57c262d8660bba60ed74ccd3f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
