name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6aa8a2f06aeb7e801e99f0d841f46a32f63d4fe8967c2cdaa729437fadac4a68"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
