name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f494b692fb0871ad145c571d3ce4a8b620acf4c6e37c67cf8fe4a12f30d49876"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
