name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c7e684453885818e9b8b71c992df649f106f3c7d5c96465eba16cc57d0119004"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
