name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "08b1a5f9d893c687e034d80080e95a05dcbe6c91fabed52ad820c3344ee3bd61"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
