name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7f919533fccc964f2733745bf504e9238ef8e8987312c27871b4cc8dcaa050dd"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
