name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ad200d929b89a1454caa4f8dc3e7cdf4239d530c5b597438e664c09bf258527e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
