name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3517ee2e37c221aed1fef5106b71966ca9dd0ef54640c280eaa431f767cb88d3"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
