name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a1292cd3d84ca5905c0e87cd2ff32ada3d6d55f3f816431239165b16a3cb45cb"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
