name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "54399def5f4e0fb7d779510653e63223135fe5f2c247612b3c8405f1178e8e36"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
