name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e3df18c1405bd6589d5ec924d56ba857b465cb2e90dcb57515ad191d28eaf4ed"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
