name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d02350afdda3004c85cbf92aed993ef0874312a47300f09c5fd26ae27390c040"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
