name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0e36c52b1b17d2ce2a7c9ae15ba25e0a97bfe16680c245057a58f7ae0a0a60e9"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
