name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b795d4adf8dcddba068942df155798a5d775635b4c3dac54bcad5d3a9c9fd350"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
