name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d53f891b4c00e82a734e79b11a8134cb820688e8b3478c08310ad1ab1d098134"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
