name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2b76aa1140eb8201eff4e342587578fad21ae974900914f61770a9cd3287088a"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
