name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c82e517bd47b67515579cc60a7ec0045d3e8dbcc62e262395740a45e36444800"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
