name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2aabf472b68ad74b9dde1803ff228c9bd82e811688a06e684702b9a226db93bc"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
