name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "feb9d4baa176e23555f212460c99c28b9e8ab168015479e1f69f0ef7f113bec0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
