name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "373c2763d28f89a6d5a3668117620d7ca869ee04c197ac43d8bf965f2ff6151b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
