name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e8173d71c1a38b6c7587db5ca3b23a046c5d1e061beb71c07449c86f1211f16e"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
