name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2c9feea6c2e0161b9f10e9a9b8f4d671273627b241cd8fd08e5ab9021fe49160"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
