name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c199ff69959eb11c4baa3c2aa17db26279e782c5fcb3bb242c5dd1784ef28fb4"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
