name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b8e0a2827851edfbc6ce5ce166c636e343fc06a2832a12230531eb909edbcca5"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
