name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "613ac22a1d1fa0f3a1c89bf58ecae4f749daf3adcc9dff75c634bd964b3ba302"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
