name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "80cb18127d9d02193804d48e2e026c3078ff9bf2f8672be3716772f87932db4c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
