name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4b6f97a142622dac4686035d7aec83b191bf2cfeb71773345907c2edd3f10cc5"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
