name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3920190a9eef971a1f27fb93fa82a86e4a508797129b1f6463c2e0e1f91107e0"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
