name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e1ce3d61a90f0403f43292029bc7f550815543348daa2c95ef603d98a498e01f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
