name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2bc7f63989bfeace074a86df4605e291c73b3801aad2bd3ee147e2669b40f092"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
