name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "721f86effef4b11ac65963fb722f6c00580f36c7049fd4d5995b9f6e44dce153"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
