name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a81178517d1c29230a3321f181e9efdc2aafb8277e0a842f3b2490eb90d1e65b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
