name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "dacdf6804d61f1f3f28820990b4aa4126e2361b4aee45ba6eb7e232ac7394892"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
