name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9cab8f1adcd9fa02e69b7116989a7c11d79abc5a28257e072dc07df63f00d8ba"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
