name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2aeeefb9913d5479730174a92c0e9c3f7da8ffc81c71ee31f3a871095a78ca92"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
