name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "a07dc031ac6a683599d561fdfa629f6b7729d8410fecfd9d7c2326d312d60864"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
