name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "20fb438d4b5b341f690c2073c89f781bf4c6ebd3307c5ebff18b821f30dc811b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
