name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c68eb33c3a7980762a1030f6de9335e93e3ed55b6d7825d2c5f924b06986332b"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
