name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "441a05a274c6a4906b263b6efe0d537d650266ee26740f132142dc1d6213d112"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
