name = "Dartis-Craft - Karui-2-packwiz"
author = "Dartis XUI"
version = "2.5.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3344d6f4a15d52ba2c87c2dead87c527e7152b4cc385ffdb1356b591d84c1df7"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
