name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e4289378ac17408cb2faaf8fc959adddc4288570766e7a1b9a6f91d49697231f"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
