name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "86a72ffd9119c6feea9aeeedb4f5981a17d90de9e5d9687a2bd9c2eb144c8b7d"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
