name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7bb0a350c78f4e339168aa26243186a7807f2d1111e962705c3967478397656c"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
