name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bb8323a1824b0441497ed3ff71f22470805db58dbad0d80c57f055e46fdb82e6"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
