name = "Dartis-Craft - Vanilla Plus Ultra 2 Packwiz"
author = "Dartis XUI"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5dfa3463cdbbb3e10be14d7a00c7706bcd971c731a56e367e8853761fe2b6135"

[versions]
forge = "14.23.5.2860"
minecraft = "1.12.2"
